"""
AI analysis and clinical report models.

Architecture decisions:

1. AIAnalysis is linked to a game_session.
   agent_type identifies which analysis agent ran.

2. Clinical reports use structured text columns (situation, background, assessment,
   recommendation) rather than a single JSONB blob. This makes the SBAR structure
   explicit, queryable, and easier to display in a UI without parsing.

3. These are AI-assisted DECISION SUPPORT tools, NOT diagnostic systems.
   All labels, UI copy, and API responses must avoid diagnostic language.
   See docs/architecture.md for the ethical framing guidelines.

4. Status field on AIAnalysis allows async processing:
   - Create record with status='pending' immediately after session upload.
   - Background process fills in result and sets status='completed'.
   - Flutter polls GET /game-sessions/{id}/analysis for status.
   Currently implemented synchronously (no background workers).
   Add Celery/BackgroundTasks later if processing time exceeds acceptable latency.
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Enum as SAEnum, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.base import Base


# ── Enums ─────────────────────────────────────────────────────────────────────

class AIAnalysisStatus(str, enum.Enum):
    pending = "pending"
    completed = "completed"
    failed = "failed"


class AgentType(str, enum.Enum):
    difficulty = "difficulty"           # Dynamic difficulty adjustment
    form_correction = "form_correction" # Movement quality analysis
    fatigue = "fatigue"                 # Fatigue indicator detection
    clinical_summary = "clinical_summary"  # SBAR report generation


# ── Models ────────────────────────────────────────────────────────────────────

class AIAnalysis(Base):
    """
    Output from an AI/agentic analysis run on session data.
    result is JSONB because output structure varies significantly per agent_type.

    IMPORTANT: result values are rehabilitation analytics indicators,
    NOT clinical diagnoses. Ensure all UI and API consumers apply
    appropriate framing (see docs/architecture.md).
    """
    __tablename__ = "ai_analyses"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    game_session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("game_sessions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    agent_type: Mapped[AgentType] = mapped_column(
        SAEnum(AgentType, name="agent_type"), nullable=False
    )
    status: Mapped[AIAnalysisStatus] = mapped_column(
        SAEnum(AIAnalysisStatus, name="ai_analysis_status"),
        nullable=False,
        default=AIAnalysisStatus.pending,
    )
    result: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    model_version: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    confidence: Mapped[Optional[float]] = mapped_column(nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    patient: Mapped["Patient"] = relationship("Patient", back_populates="ai_analyses")
    game_session: Mapped[Optional["GameSession"]] = relationship(
        "GameSession", back_populates="ai_analyses"
    )


class ClinicalReport(Base):
    """
    Structured SBAR clinical summary report.
    Generated by the clinical_summary agent or manually by a doctor.

    SBAR: Situation | Background | Assessment | Recommendation
    Using structured text columns (not a single JSONB blob) makes the format
    explicit, each section easily queryable, and UI rendering straightforward.

    generated_by: 'ai_agent' | 'manual' — distinguishes AI-generated from
    doctor-authored reports. Doctors should always review AI-generated reports.
    """
    __tablename__ = "clinical_reports"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("doctors.id"),
        nullable=False,
        index=True,
    )
    # SBAR fields
    situation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    background: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    assessment: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    recommendation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    generated_by: Mapped[str] = mapped_column(
        String(50), nullable=False, default="manual",
        comment="'ai_agent' or 'manual'",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    patient: Mapped["Patient"] = relationship("Patient", back_populates="clinical_reports")
    doctor: Mapped["Doctor"] = relationship("Doctor", back_populates="clinical_reports")
