"""initial_schema

Revision ID: 6db42d6dfe5a
Revises: 
Create Date: 2026-09-05 19:03:58.336177

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6db42d6dfe5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_identifier', sa.String(length=100), nullable=False, comment='BLE MAC address or unique hardware ID'),
    sa.Column('ble_name', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Updated by Flutter app on each BLE connection'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_identifier'), 'devices', ['device_identifier'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable name, e.g. 'Piano'"),
    sa.Column('slug', sa.String(length=50), nullable=False, comment="Machine-readable identifier, e.g. 'piano' or 'pick_and_place'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='Must equal Supabase auth.users.id (JWT sub claim)'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'patient', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('stroke_date', sa.Date(), nullable=True, comment='Date of stroke event — clinical context, not a diagnosis'),
    sa.Column('affected_side', sa.String(length=20), nullable=True, comment='left | right | bilateral'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Non-diagnostic clinical notes by the doctor'),
    sa.Column('created_by_doctor_id', sa.UUID(), nullable=True, comment='The doctor who created this patient account'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_by_doctor_id'), 'patients', ['created_by_doctor_id'], unique=False)
    op.create_table('device_calibrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('flex_min', postgresql.ARRAY(sa.Float()), nullable=True, comment='Raw ADC values at full extension, per finger [f1, f2, f3]'),
    sa.Column('flex_max', postgresql.ARRAY(sa.Float()), nullable=True, comment='Raw ADC values at full flexion, per finger [f1, f2, f3]'),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_calibrations_device_id'), 'device_calibrations', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_calibrations_patient_id'), 'device_calibrations', ['patient_id'], unique=False)
    op.create_table('doctor_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'transferred', name='relationship_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patients_doctor_id'), 'doctor_patients', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_patient_id'), 'doctor_patients', ['patient_id'], unique=False)
    op.create_table('patient_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_devices_device_id'), 'patient_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_patient_devices_patient_id'), 'patient_devices', ['patient_id'], unique=False)
    op.create_table('patient_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False, comment='bcrypt hash of the 6-digit PIN'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_invitations_patient_id'), 'patient_invitations', ['patient_id'], unique=False)
    op.create_table('therapy_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Client-generated UUID v4 (enables idempotent retry on upload failure)'),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True, comment='Nullable: session may occur without a glove (future UI-only mode)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Session start time as recorded by Flutter (device clock)'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True, comment='Total session duration in seconds'),
    sa.Column('status', sa.Enum('completed', 'abandoned', 'interrupted', name='session_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_sessions_patient_id'), 'therapy_sessions', ['patient_id'], unique=False)
    op.create_table('clinical_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('therapy_session_id', sa.UUID(), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=False, comment="'ai_agent' or 'manual'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapy_session_id'], ['therapy_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_reports_doctor_id'), 'clinical_reports', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_clinical_reports_patient_id'), 'clinical_reports', ['patient_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Client-generated UUID v4'),
    sa.Column('therapy_session_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('calibration_id', sa.UUID(), nullable=True, comment='The calibration active at the time of this session'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='Game duration in milliseconds'),
    sa.Column('status', sa.Enum('completed', 'abandoned', 'interrupted', name='session_status'), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Game config at session time. Examples:\n  Piano:       {difficulty:2, tempo_bpm:80, target_notes:30}\n  Pick-Place:  {difficulty:3, object_count:10, object_speed:1.2}'),
    sa.Column('game_version', sa.String(length=50), nullable=True, comment='Version of the game/Flutter app that ran this session'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['device_calibrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['therapy_session_id'], ['therapy_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_game_id'), 'game_sessions', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_therapy_session_id'), 'game_sessions', ['therapy_session_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('game_session_id', sa.UUID(), nullable=True),
    sa.Column('therapy_session_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('difficulty', 'form_correction', 'fatigue', 'clinical_summary', name='agent_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='ai_analysis_status'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapy_session_id'], ['therapy_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_game_session_id'), 'ai_analyses', ['game_session_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_patient_id'), 'ai_analyses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_therapy_session_id'), 'ai_analyses', ['therapy_session_id'], unique=False)
    op.create_table('game_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_session_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True, comment='0.0–1.0'),
    sa.Column('completion_rate', sa.Float(), nullable=True, comment='0.0–1.0, fraction of game objectives completed'),
    sa.Column('repetitions', sa.Integer(), nullable=True, comment='Total repetitions (notes played, objects picked, etc.)'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Game-specific metrics. Examples:\n  Piano: {notes_hit:42, notes_missed:8, avg_reaction_ms:420,\n          finger_accuracy:{finger_1:0.94, finger_2:0.88, finger_3:0.91}}\n  Pick-Place: {objects_picked:12, objects_missed:2, avg_pick_ms:850,\n               movement_velocity:1.42, movement_smoothness:0.81}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_game_session_id'), 'game_results', ['game_session_id'], unique=True)
    op.create_table('session_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_session_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_metrics_game_session_id'), 'session_metrics', ['game_session_id'], unique=True)
    # ### end Alembic commands ###

    # ── Seed initial game registry ─────────────────────────────────────────────
    # Adding a future game only requires inserting a new row here (or a new migration).
    # No schema change is needed for new game types.
    games_table = sa.table(
        "games",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("slug", sa.String()),
        sa.column("description", sa.String()),
        sa.column("version", sa.String()),
        sa.column("is_active", sa.Boolean()),
    )
    op.bulk_insert(games_table, [
        {
            "id": str(uuid.uuid4()),
            "name": "Piano",
            "slug": "piano",
            "description": (
                "Fine motor skill training via finger-activated piano tiles. "
                "Trains finger flexion, timing, and activation control."
            ),
            "version": "1.0",
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name": "Pick and Place",
            "slug": "pick_and_place",
            "description": (
                "Hand/wrist coordination training using MPU6050 motion. "
                "Trains controlled movement, velocity, and wrist stability."
            ),
            "version": "1.0",
            "is_active": True,
        },
    ])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_metrics_game_session_id'), table_name='session_metrics')
    op.drop_table('session_metrics')
    op.drop_index(op.f('ix_game_results_game_session_id'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_index(op.f('ix_ai_analyses_therapy_session_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_patient_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_game_session_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_game_sessions_therapy_session_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_game_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_clinical_reports_patient_id'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_doctor_id'), table_name='clinical_reports')
    op.drop_table('clinical_reports')
    op.drop_index(op.f('ix_therapy_sessions_patient_id'), table_name='therapy_sessions')
    op.drop_table('therapy_sessions')
    op.drop_index(op.f('ix_patient_invitations_patient_id'), table_name='patient_invitations')
    op.drop_table('patient_invitations')
    op.drop_index(op.f('ix_patient_devices_patient_id'), table_name='patient_devices')
    op.drop_index(op.f('ix_patient_devices_device_id'), table_name='patient_devices')
    op.drop_table('patient_devices')
    op.drop_index(op.f('ix_doctor_patients_patient_id'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_doctor_id'), table_name='doctor_patients')
    op.drop_table('doctor_patients')
    op.drop_index(op.f('ix_device_calibrations_patient_id'), table_name='device_calibrations')
    op.drop_index(op.f('ix_device_calibrations_device_id'), table_name='device_calibrations')
    op.drop_table('device_calibrations')
    op.drop_index(op.f('ix_patients_created_by_doctor_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_devices_device_identifier'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
